# Built in classes in python

In [4]:
age = 23
print(age)
print(f"I am {age} years old")
print(type(age))

23
I am 23 years old
<class 'int'>

In [5]:
b = [1 , 4, 5, 8, 9]
print(type(b))

<class 'list'>

In [6]:
m = True
print(type(m))

<class 'bool'>

In [7]:
# method of class list
b.append(10)
print(b)

[1, 4, 5, 8, 9, 10]

In [8]:
c =(2, 3, 4, 5, 6)
print(type(c))

<class 'tuple'>

In [1]:
import pandas as pd

df = pd.DataFrame(
    {
        "id":[1, 2, 3],
        "name":["shubham", "rohit","rahul"],
        "age": [23, 22, 24],
        "height":[5.6, 6.4,5.7]

    }
)

In [2]:
df

   id     name  age  height
0   1  shubham   23     5.6
1   2    rohit   22     6.4
2   3    rahul   24     5.7

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

# Attibute of classes

In [5]:
df.columns

Index(['id', 'name', 'age', 'height'], dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [7]:
df.values

array([[1, 'shubham', 23, 5.6],
       [2, 'rohit', 22, 6.4],
       [3, 'rahul', 24, 5.7]], dtype=object)

In [9]:
df.shape

(3, 4)

In [10]:
df.size

12

In [11]:
df.dtypes

id          int64
name       object
age         int64
height    float64
dtype: object

# methods of class dataframe

In [13]:
df.sort_values(by = "age",ascending = True)

   id     name  age  height
1   2    rohit   22     6.4
0   1  shubham   23     5.6
2   3    rahul   24     5.7

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   name    3 non-null      object
 2   age     3 non-null      int64
 3   height  3 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 228.0+ bytes

# Create a class person

1. attributes - properties of the class
2. methods  - perform certain operations based on attribute

In [19]:
class Person:
    # constructor functions _init_ to define attributes of class
    # Self is any object of class person
    def __init__(self, name: str, age: int, gender: str, occupation: str):
        self.name = name
        self.age = age
        self.gender = gender
        self.occupation = occupation

    # this function is the string representation of the class
    def __str__(self):
        return f"Person(name={self.name}, age={self.age}, gender={self.gender}, occupation={self.occupation})"

    # write a method for a class person
    def introduce(self):
        print(f"My name is {self.name}")
        print(f"My age is {self.age}")
        print(f"I am {self.gender}")
        print(f"I work as {self.occupation}")

In [22]:
# p1 is object of class person
p1 = Person(name="shubham", age=23, gender="male", occupation="data analyst")
print(type(p1))

<class '__main__.Person'>

In [23]:
p1

In [25]:
print(p1)

Person(name=shubham, age=23, gender=male, occupation=data analyst)

In [26]:
p1.name

'shubham'

In [27]:
p1.age

23

In [28]:
p1.gender

'male'

In [29]:
p1.occupation

'data analyst'

In [30]:
p1.introduce()

My name is shubham
My age is 23
I am male
I work as data analyst

In [31]:
p2 = Person(name = "Aditi", age=20, gender="female", occupation="Sales")
print(type(p2))

<class '__main__.Person'>

In [32]:
p2.name

'Aditi'

In [33]:
p2.age

20

In [34]:
p2.gender

'female'

In [35]:
p2.occupation

'Sales'

In [37]:
p2.introduce()

My name is Aditi
My age is 20
I am female
I work as Sales

In [38]:
print(p2)

Person(name=Aditi, age=20, gender=female, occupation=Sales)

# data classes

In [2]:
from dataclasses import dataclass
from typing import Literal

@dataclass
class Person2:
    name: str
    age: int
    gender: Literal["male", "female"]
    occupation: str

    def intro(self):
        print(f"My name is {self.name}")
        print(f"My age is {self.age}")
        print(f"I am {self.gender}")
        print(f"I work as {self.occupation}")

In [3]:
p3 = Person2(name="shubham", age=23, gender="male", occupation="data analyst")
print(p3)

Person2(name='shubham', age=23, gender='male', occupation='data analyst')

In [4]:
print(type(p3))

<class '__main__.Person2'>

In [5]:
p3.name

'shubham'

In [6]:
p3.age

23

In [7]:
p3.gender

'male'

In [8]:
p3.occupation

'data analyst'

In [9]:
p3.intro()

My name is shubham
My age is 23
I am male
I work as data analyst

In [10]:
p4 = Person2(name="Rohit", age=24, gender="male", occupation="data analyst")
print(p4)

Person2(name='Rohit', age=24, gender='male', occupation='data analyst')

In [11]:
p4.name

'Rohit'

In [12]:
p4.age

24

In [13]:
p4.gender

'male'

In [15]:
p4.occupation

'data analyst'

In [16]:
@dataclass
class Account:
    ac_no: int
    name: str
    balance: float

    def check_balance(self):
        print(f"Account number {self.ac_no}, Name : {self.name}, Balance : {self.balance}")

    def deposit(self, amt: float):
        if amt<=0:
            raise ValueError("The amount deposited cannot be negative or zero")
        self.balance = self.balance +amt

    def withdraw(self, amt: float):
        if amt <=0:
            raise ValueError("The ammount withdrawn cannot be negative or zero")
        if amt > self.balance:
            raise ValueError("Insufficient banlance")
        self.balance = self.balance - amt       

    def transfer(self, amt: float, other_ac: 'Account'):
        self.withdraw(amt)
        other_ac.deposit(amt)

In [17]:
ac1 = Account(ac_no= 1342, name= "shubham", balance=1000000)
print(ac1)

Account(ac_no=1342, name='shubham', balance=1000000)

In [19]:
ac1.check_balance()

Account number 1342, Name : shubham, Balance : 1000000

In [20]:
ac1.withdraw(100001)

In [21]:
ac1.balance

899999

# creating other account

In [22]:
ac2 = Account(ac_no=3425, name="rohit", balance=90876)
print(ac2)

Account(ac_no=3425, name='rohit', balance=90876)

In [23]:
ac2.deposit(34)

In [25]:
ac2.check_balance()

Account number 3425, Name : rohit, Balance : 90910

In [26]:
ac2.withdraw(910)

In [27]:
ac2.check_balance()

Account number 3425, Name : rohit, Balance : 90000

In [28]:
ac2.transfer(1342, ac1)

In [29]:
ac1.check_balance()
ac2.check_balance()

Account number 1342, Name : shubham, Balance : 901341
Account number 3425, Name : rohit, Balance : 88658